spring:
  application:
    name: invoice-service
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          multiplier: 2.0

sepay:
  username: ${SEPAY_USERNAME}
  password: ${SEPAY_PASSWORD}
  auth-url: ${SEPAY_INVOICE_AUTH_URL}
  create-url: ${SEPAY_INVOICE_CREATE_URL}
  check-url: ${SEPAY_INVOICE_CHECK_URL}

server:
  port: 8081
