@startuml
!include <C4/C4_Component>

title Luồng gửi SMS OTP

Person(customer, "Customer", "Khách hàng")

System_Ext(twilio, "Twilio Verify", "Dịch vụ xác thực SMS")

System_Boundary(storeSystem, "SLY Store System") {
    Container_Boundary(server, "Server") {
        Boundary(ctrlBoundary, "Controller") {
            Component(authCtrl, "Auth Controller", "Spring MVC Controller", "Tiếp nhận request từ Frontend")
        }

        Boundary(svcBoundary, "Service") {
            Component(smsVerifySvc, "SMS Verification Service", "Spring Service")
        }

        Boundary(consumerBoundary, "Event Consumer") {
            Component(smsEventProducer, "SMS Event Producer", "Spring Component")
        }

        Boundary(producerBoundary, "Event Producer") {
            Component(smsEventConsumer, "SMS Event Consumer", "Spring Component")
        }
    }

    ContainerQueue(msgBroker, "Message Broker", "RabbitMQ") {
        queue "OtpRequestedEvent" as otpRequestedQueue
    }

    ContainerDb(azureRedis, "Redis Cache", "Azure Managed Redis", "Lưu trữ Cache")
}

Rel(customer, authCtrl, "Yêu cầu gửi SMS OTP")

Rel(authCtrl, smsVerifySvc, "Gửi OTP")

Rel(smsVerifySvc, azureRedis, "Kiểm tra hoặc Lưu hạn sử dụng OTP")
Rel(smsVerifySvc, smsEventProducer, "")

Rel(smsEventProducer, otpRequestedQueue, "")
Rel(otpRequestedQueue, smsEventConsumer, "")

Rel(smsEventConsumer, twilio, "Yêu cầu gửi SMS OTP")

@enduml
