@startuml
!include <C4/C4_Container>
title SLY Clothing Store Project - Container Diagram
Person(guest, "Guest", "Khách vãng lai")
Person(customer, "Customer", "Khách hàng")
Person(employee, "Employee", "Nhân viên bán hàng")
Person(admin, "Admin", "Chủ cửa hàng")

System_Boundary(storeSystem, "Store System") {
    Container(reactSPA, "Web", "React and TypeScript", "Giao diện web admin")
    Container(springAPI, "Server", "Spring Boot", "REST API Server và Giao diện khách hàng")
}

System_Ext(sepay, "SePay Payment Gateway", "Cổng thanh toán")
System_Ext(gmail, "Gmail SMTP Service", "Dịch vụ email")

System_Boundary(azure, "Azure Managed Services") {
    ContainerDb_Ext(azureMySQL, "SQL Database", "Azure Database for MySQL", "Cơ sở dữ liệu")
    ContainerDb_Ext(azureBlob, "Object storage", "Azure Blob Storage", "Lưu trữ hình ảnh")
    ContainerDb_Ext(azureRedis, "Redis Cache", "Azure Managed Redis", "Lưu trữ Session / Cache")
}

Rel(guest, springAPI, "Xem sản phẩm", "HTTPS")
Rel(customer, springAPI, "Đặt hàng, chat", "HTTPS / WSS")
Rel(employee, reactSPA, "Xử lý đơn hàng, chat tư vấn", "HTTPS / WSS")
Rel(admin, reactSPA, "Quản lý sản phẩm", "HTTPS / WSS")
Rel(reactSPA, springAPI, "Gọi REST API", "HTTPS")
Rel(springAPI, azureRedis, "Session, cache", "HTTPS")
Rel(springAPI, azureMySQL, "CRUD dữ liệu", "JDBC / ORM")
Rel(springAPI, azureBlob, "Upload/download hình ảnh", "Azure SDK / HTTPS")
Rel(springAPI, gmail, "Gửi email xác nhận", "SMTP")
Rel(sepay, springAPI, "Gửi Webhook thanh toán", "HTTPS POST")
@enduml