@startuml
!include <C4/C4_Container>

title SLY Clothing Store Project - Container Diagram

Person(guest, "Guest", "Khách vãng lai")
Person(customer, "Customer", "Khách hàng")
Person(employee, "Employee", "Nhân viên bán hàng")
Person(admin, "Admin", "Chủ cửa hàng")

System_Boundary(storeSystem, "SLY Store System") {
    Container(webAdmin, "Web Admin", "React and TypeScript", "Giao diện web admin")
    Container(server, "Server", "Spring Boot with Thymeleaf", "Giao diện khách hàng và REST API Server")
}

System_Ext(sepay, "SePay Payment Gateway", "Cổng thanh toán")
System_Ext(gmail, "Gmail SMTP Service", "Dịch vụ email")
System_Ext(twilio, "Twilio Verify", "Dịch vụ xác thực SMS")

System_Boundary(azure, "Azure Managed Services") {
    ContainerDb_Ext(azureMySQL, "SQL Database", "Azure Database for MySQL", "Cơ sở dữ liệu")
    Container_Ext(azureBlob, "Object storage", "Azure Blob Storage", "Lưu trữ hình ảnh")
    ContainerDb_Ext(azureRedis, "Redis Cache", "Azure Managed Redis", "Lưu trữ Session / Cache")
}

Rel(guest, server, "Xem sản phẩm", "HTTPS")
Rel(customer, server, "Đặt hàng, chat", "HTTPS / WSS")
Rel(employee, webAdmin, "Xử lý đơn hàng, chat", "HTTPS / WSS")
Rel(admin, webAdmin, "Quản lý sản phẩm", "HTTPS / WSS")

Rel(webAdmin, server, "Gọi REST API", "HTTPS")

Rel(server, azureRedis, "Session, cache", "HTTPS")
Rel(server, azureMySQL, "CRUD dữ liệu", "JDBC / ORM")
Rel(server, azureBlob, "Upload/download hình ảnh", "Azure SDK / HTTPS")
Rel(server, gmail, "Gửi email xác nhận", "SMTP")
Rel(server, twilio, "Gửi OTP", "Twilio SDK / HTTPS")

Rel_U(sepay, server, "Gửi Webhook thanh toán", "HTTPS POST")
@enduml