name: deploy-workflow.yml

on:
  workflow_run:
    workflows: [ build-workflow.yml ]
    types: [ completed ]
    branches:
      - main

permissions:
  contents: read
  actions: write

env:
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  terraform-plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -no-color -out=tfplan -input=false
